apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-alsy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-alsy
    app.kubernetes.io/part-of: build-suite-component-update-zsth
  name: multi-component-child-alsy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-child-alsy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-child-alsy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-goxv-tenant/build-suite-component-update-zsth/multi-component-child-alsy@sha256:8ec5c57492072045ae5d54f6d4ffc070792bbd100dcd4bdb687d3516f6c4bdbd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
